language: ruby

sudo: false

rvm: jruby-18mode
jdk: oraclejdk8

cache:
  - bundler
  - /home/travis/.rvm

env:
  - JRUBY_OPTS=--dev --debug -Xcompile.invokedynamic=true
gemfile:
  - Gemfile

before_install:
  - gem update --system
  - gem install bundler
