language: ruby
sudo: false

cache:
  directories:
    - vendor/bundle

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler

jobs:
  include:
    - stage: Ruby bundle
      script: bundle install --path=vendor/bundle
    - stage: Create Docker image
      script: docker build -t homie-monitor .
    - stage: test
      script: docker run --rm --name my-homie-monitor homie-monitor
