language: ruby

sudo: false

cache:
  - bundler
  - /home/travis/.rvm

env:
  - JRUBY_OPTS: --dev --debug -Xcompile.invokedynamic=true

services:
  - docker

before_install:
  - gem update --system
  - gem install bundler

jobs:
  include:
    - stage: Ruby bundle
      script: bundle install --path=vendor/bundle
    - stage: Create Docker image
      script: docker build -t homie-monitor .
