language: ruby

sudo: false

rvm: jruby-18mode
jdk: oraclejdk8

cache:
  - bundler
  - /home/travis/.rvm

gemfile:
  - Gemfile

before_script:
  - export JRUBY_OPTS=--dev --debug -Xcompile.invokedynamic=true

before_install:
  - gem update --system
  - gem install bundler
