version: '3.2'
services:
  homieMonitor:
    container_name: homieMonitor
    environment:
      - RACK_ENV=production
      - BUNDLE_PATH=vendor/bundle
    image: skoona/homie-monitor
    ports:
      - target: 8585
        published: 8585
        protocol: tcp
        mode: host
    restart: always
    tty: true
    volumes:
      - configs:/config
      - store:/content
      - logs:/log

volumes:
  configs:
  store:
  logs:

