version: '3.2'
services:
  homieMonitor:
    container_name: homieMonitor
    environment:
      - RACK_ENV=production
    image: skoona/homie-monitor:latest
    #image: homie-monitor #from local repro
    ports:
      - target: 8585
        published: 8585
        protocol: tcp
        mode: host
    restart: always
    tty: true
    volumes:
      - type: bind
        source: ./srv/homieMonitor/tmp
        target: /tmp
      - type: bind
        source: ./srv/homieMonitor/
        target: /usr/src/app
