---
Packaging:
  pgmName: HomieMonitor
  releaseVersion: <%= Skn::Version %>
  isTest: false
  isDevelopment: false
  isStaging: false
  isProduction: false
  configName: base
  short_name: esp

skn_base:
  secret: 37ae095d4e6ad226c79a03393f743d6c4d51b19fd8f6850e9ce5041312e631f6f9f7b10192ccd29c9ca4e75bff4207929304132849d0defc803a926406bbb676
  session_key: _skn_web_homie_session
  session_domain: .skoona.net

content_service:
  demo_mode: false
  description: Homie Monitor
  firmware_path: <%= ENV.fetch('HM_FIRMWARE_PATH', "./content/firmwares/") %>
  spiffs_path: <%= ENV.fetch('HM_SPIFFS_PATH', "./content/spiffs/") %>
  data_source:
    store: <%= ENV.fetch('HM_DATA_STORE', "./db/HomieMonitor_store.yml") %>
  ota:
    type: <%= ENV.fetch('HM_OTA_TYPE', "binary") %>

# ##
# Override (restate) by development, stage, production, etc
mqtt:
  host: <%= ENV.fetch('HM_MQTT_HOST', "some.fqdn.com") %>
  port: <%= ENV.fetch('HM_MQTT_PORT', 1883) %>
  username: <%= ENV.fetch('HM_MQTT_USER', "userid") %>
  password: <%= ENV.fetch('HM_MQTT_PASS', "password") %>
  env_base_topics: <%= ENV['HM_BASE_TOPICS'] %>
  # [["sknSensors/#", 2], ["homie/#", 2]]
  :base_topics:
    - - sknSensors/#
      - 2
    - - homie/#
      - 2
  debug_log_file: <%= ENV.fetch('HM_MQTT_LOG', '/tmp/homieMonitor/paho-debug.log') %>
  ssl_enable: <%= ENV.fetch('HM_MQTT_SSL_ENABLE_FLAG', false) %>
  ssl_certificate_path: <%= ENV.fetch('HM_MQTT_SSL_CERT_PATH', nil) %>
  ssl_key_path: <%= ENV.fetch('HM_MQTT_SSL_KEY_PATH', nil) %>
